### PR TITLE
Update bedrock-autoloader and object-cache from upstream

### PR DESCRIPTION
**Pull request by l3ku**
While investigating a separate issue, I updated the files from upstream. While the issue was ultimately not due to these files, I don't just want to throw away the work for updating these files and I think it is good practice to regularly update them. For instance, the last time bedrock-autoloader was updated was 4 years ago (although no big changes have been added since).

### CODE REVIEW

**Comment by ottok** [comment]
The Bedrock autoloader in particular should be tested manually on multiple sites (old, new, normal, networks etc) before we merge this.

**Comment by ottok** [comment]
Bedrock has very few new commits and the commit titles don't state any features or fixes that improve the functionality:
image

I cannot spot anything useful in the Redis plugin changes either. I am a bit afraid of updating these just for the sake of updating if there is nothing useful in them, as they might introduce regressions in vain.

**Comment by l3ku** [comment]
> I am a bit afraid of updating these just for the sake of updating if there is nothing useful in them, as they might introduce regressions in vain.

Agree, closing.

**Comment by ottok** [comment]
Re-opening. We could do this, but with a low priority and a lot of testing for regressions.

**Comment by ottok** [comment]
This was obsoleted by newer changes in 78a299aed667abea15f02336ae1746efade8a5b3 and a2feffb49342d6eae0c17fc51edb5b257c002c4e

**Pull request closed without merging**
