### PR TITLE
Update dotenv to version 2.4.0

### LINKED ISSUE #36: Version 2.x of phpdotenv
We're currently using version 1.0.9 of phpdotenv. The new version has apparently changed its API slightly.

The trouble with this is that because composer libs are global, and some plugins using the composer autoloader might want to use a different version of dotenv, which wont work between 1.x and 2.x. 

We should maybe start supporting the 2.x version of phpdotenv, if it turns out lots of plugins are using the newest version.

### PR DESCRIPTION
**Pull request by t-my**
Mutable env files are loaded with `Dotenv->overload()`.

* I faced some issues with dotenv 1.x with one plugin and I'm currently running something like this
* Not tested, maybe some of core contributors could test this
* composer.lock updated by hand, maybe you want to update it?

Fixes #36

### CODE REVIEW

**Comment by ottok** [comment]
Thanks for the PR! We will review this shortly.

**Comment by tnottu** [comment]
My 2 cents: we have used dotenv version 2.x for over a year now, for all our sites in Seravo / WP-palvelu. So far we have not had any problems from this. So, seems like a good update to me.

**Comment by ypcs** [comment]
Thank you very much for the PR, and sorry for a very long delay.

While doing initial testing for this I encountered some issues, but while retesting I wasn't able to reproduce errors.

(For reference, tested in existing + new containers.)

**Comment by ottok** [comment]
Note to self: the dotenv version will be installed using `composer install` (or `update` into `/data/wordpress/vendor` wherever it is run. There is currently nothing enforcing that when a new version of `dotenv` is installed, the `wp-config.php` file would update. However these are being rolled out in the same commit, so there should not be any mixing of them unless the developer specifically update their own `composer.json` file themselves. We never update is post deploy. **However**, we might update the `wp-config.php` file post deploy, which would break any existing `.env` setups.

**Pull request merged**
