### PR TITLE
Add WP_DEVELOPMENT_MODE.

### LINKED ISSUE #214: Consider adding `WP_DEVELOPMENT_MODE`
There has been some caching related changes in recent WP releases.

- [Improvements to Template Loading in WordPress 6.4](https://make.wordpress.org/core/2023/10/17/improvements-to-template-loading-in-wordpress-6-4/)
- [Configuring development mode in 6.3](https://make.wordpress.org/core/2023/07/14/configuring-development-mode-in-6-3/)

In short, when developing a site, `theme.json` and patterns are cached. This makes it annoying to develop since the changes are not seen right away.

When in DEV my suggestion is to add `define( 'WP_DEVELOPMENT_MODE', 'all' );`. Maybe in `wp-config.php`:

```php
/**
 * For developers: show verbose debugging output if not in production.
 */
if ( 'production' === getenv('WP_ENV') ) {
  define('WP_DEBUG', false);
  define('WP_DEBUG_DISPLAY', false);
  define('WP_DEBUG_LOG', false);
  define('SCRIPT_DEBUG', false);
} else {
  define('WP_DEBUG', true);
  define('WP_DEBUG_DISPLAY', true);
  define('WP_DEBUG_LOG', '/data/log/php-error.log');
  define('SCRIPT_DEBUG', true);
  // Added in here.
  define('WP_DEVELOPMENT_MODE', 'all');
}
```

### PR DESCRIPTION
**Pull request by samikeijonen**
See details in #214.

Closes #214

### CODE REVIEW

**Comment by samikeijonen** [comment]
Any news on this one?

**Comment by ypcs** [comment]
Hi,

Thanks for the contribution. Could you drop the ending period (`.`) from the commit message and add links to upstream docs in the commit message to provide some context.

Other than that, looks good and improves the default project template.

Thanks!

**Review by ypcs — CHANGES_REQUESTED** [review]
See separate comment: some additional context / links to upstream docs to commit message + remove ending period from the commit message subject. Other than that this is really good improvement to the project and change itself is good.

**Comment by ypcs** [comment]
Hi,

I added some context to the commit message, and merged your changes. Thanks for the contribution @samikeijonen! :)

**Pull request closed without merging**
