### PR TITLE
Run Travis CI tests inside our CI image via a .seravo-ci test script

### PR DESCRIPTION
**Pull request by l3ku**
With this change into our project template, developers starting to develop
their projects on this template can just focus on having the right tests
in the .seravo-ci file, and Travis CI is already configured to start a
container from our CI Docker image. The .seravo-ci file contains some
example content.

### CODE REVIEW

**Comment by ottok** [comment]
Looks good! Do we need more testing or some rollout plan?

**Comment by l3ku** [comment]
The only rollout plan that comes to my mind is that there needs to be something mentioned about this in https://seravo.com/docs. Maybe also a potential mention in the blog article that you had planned for announcing the recent Docker renovations.

**Comment by elguitar** [comment]
We will continue from here :)

**Review by elguitar — APPROVED** [review]
Nice! Feel free to merge

**Pull request merged**
